version: 2.0

jobs:
  "node-14":
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm ci
      - run:
          name: Run tests
          command: npm test
  "node-12":
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm ci
      - run:
          name: Run tests
          command: npm test
workflows:
  version: 2
  build:
    jobs:
      - "node-14"
      - "node-12"
